// TIPE DATA BOOLEAN ADALAH DATA YANG BERISIKAN DATA KEBENARAN, ARTINYA HANYA ADA DUA DATA. BENAR DAN SALAH(YES OR NO)
// BENAR DI REPRESENTASIKAN DENGAN KATA KUNCI TRUE, DAN SALAH DIREPRESENTASIKAN DENGAN KATA KUNCI FALSE
// WALAUPUN TIPE DATA BOOLEAN MERUPAKAN TIPE DATA YANG SANGAT SEDERHANA TAPI TIPE DATA BOOLEAN AKAN BANYAK DIGUNAKAN DI BERBAGAI FITUR PEMROGRAMAN

document.writeln(true); // BENAR
document.writeln("</br>");
document.writeln(false); // SALAH