// TIPE DATA STRING ATAU TEXT ADALAH TIPE DATA YANG BERISIKAN KUMPULAN KOSONG ATAU LEBIH KARAKTER

// SEBELUMNYA KITA SUDAH PERNAH MENGGUNAKAN STRING KETIKA MEMBUAT PROGRAM HELLO WORLD

// DI JAVASCRIPT UNTUK MEMBUAT DATA DENGAN TIPE DATA STRING KITA PERLU MENGGUNAKAN "(PETIK DUA) ATAU '(PETIK SATU) SEBELUM DAN SETELAH ISI TEXT NYA

document.writeln("Halo" + "Muhammad Risky");